### ISSUE TITLE
Any help needed?

### ISSUE THREAD

**Issue by VinceOPS** [aspect-build/rules_cypress#3]
Good morning!

I spent a few hours trying to make the rules_nodejs Cypress work with Aspect's rules_js and, just like it's stated in the documentation, they're not really compatible 😀.

Is there anything that the team can be helped with? Documentation, code, examples, beta testing... ? I'd be glad to help/contribute to this package!

Cheers

**Comment by gregmagolan** [comment]
HI @VinceOPS. Thanks for the offer. @mrmeku has got this one started here https://github.com/mrmeku/rules_cypress and is planning to upstream it to this repo. Need any help Dan?

**Comment by mrmeku** [comment]
Hi @VinceOPS happy to have some help with this! My intentional was not to make the rules one to one compatible for a couple of different reasons. The most notable one is that the old rule set relied on using Cypress plugins to boot a dev server / do configuration and Cypress 10 no longer supports plugin files (see https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed). 

Secondly, now that rules_js uses ES modules, we can no longer use `require` to bootstrap the cypress CLI as the old rule set did since the CLI entry point is not exported by Cypress's package.json. Between Cypress 10's new .js/.ts configuration files and the node api, I don't think we really need to use the CLI directly anymore. I think the node api is just as capable and more powerful in some meaningful respects. That being said, if we wanted to expose a separate bazel rule to run cypress via the CLI rather than the node api, I think that might be better for your use case of wanting a new rule that functions more like the old rule. That would be a welcome contribution to the repo :) 

As far as contributing to the new rule set, feel free to! The basic rule works just fine but I was planning on adding support for a more simple use case where a user doesn't want to interact with the cypress node api. In that use case we would just have the user specify a config file and we would auto generate the entry point to interact with the node api. If you wanted to hack together on that, I think that would be fun and also a welcome contribution :)

**Comment by VinceOPS** [comment]
'morning @mrmeku 

Thanks for your answer, and sorry for the delay. I'm still a bit new to Bazel but I think it's okay for me to build upon the current repo! (definitely eager to learn & contribute more, to see Bazel spread across my fav. stack 😜)

Also, has this rule been published already? If so, shall we create a release and offer a WORKSPACE?

Cheers

**Comment by mrmeku** [comment]
I'll publish this once this initial PR is merged: https://github.com/aspect-build/rules_cypress/pull/14
Thanks for you patience @VinceOPS !

**Comment by gregmagolan** [comment]
@VinceOPS Planning on a 0.0.1 tag shortly. Are you using this rule set at Jellyfish? We're going to be deploying it at a client this quarter so we'll put some miles on it and land fixes for any issues we hit.

**Comment by ss185994** [comment]
Any ETA on a release?

**Comment by alexeagle** [comment]
There's not actually an issue here, so I'm closing this. We can use GH Discussions feature if there's more chat to be had :)
