### ISSUE TITLE
[Bug]: '"Cypress.app"  is damaged and can't be opened.' error on mac.

### ISSUE THREAD

**Issue by mikelikespie** [aspect-build/rules_cypress#43]
### What happened?

When running a cypress test on macos, I am seeing a security error that won't let the app being run from the command line (without a pretty intrusive workaround).

This error comes up when running a cypress test and doesn't
<img width="668" alt="Screenshot 2023-07-17 at 5 09 52 PM" src="https://github.com/aspect-build/rules_cypress/assets/21435/446a97dd-6445-4a7f-9333-f2a064e401a8">

This appears in settings. One can work around it by hitting the "Open Anyway" button, but that isn't really tenable for having other engineers do it.
![Screenshot 2023-07-17 at 5 11 23 PM](https://github.com/aspect-build/rules_cypress/assets/21435/24a689ed-80a8-4817-bdf2-293cea206534)

### Version

Development (host) and target OS/architectures:
m1 mac
macos 13.4.1 (c) (22F770820d)

Output of `bazel --version`:
saw in both `bazel 6.2.0` and `aspect 5.2.1` (from rules_cypress clone)

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
* Clone rules_cypress
* run `bazel test //cypress/tests/cli_test:cli_test`
* It hangs and you see app is damaged warning (see screenshot above)
```

**Comment by mrmeku** [comment]
Yeah I hear you @mikelikespie. I'm honestly not sure how to fix this from within the bazel rule since this is a operating system level security setting. If you have any ideas of what can be done to address this in code please let me know and I'll implement it. But I'm sort of stuck at the ideation phase

**Comment by doncollins** [comment]
I encountered this problem as well and, after some experimentation, came to the conclusion that macOS refuses to run the binary because the copying that's done [here](https://github.com/aspect-build/rules_cypress/blob/961cc5747ee974d28e525c93687274211acb5744/cypress/BUILD.cypress#L6-L17) mangles the structure of the binary directory in some way so that macOS doesn't like it anymore, possibly by dereferencing symlinks instead of preserving them as symlinks.

We're working around this for now by patching `BUILD.cypress` to just use a `filegroup` instead of `copy_directory`. That causes macOS to run the binary without complaint (but going by the comment on that file, I assume that that will break RBE).

Do you think there's a way to copy it while keeping it intact enough to satisfy macOS?

**Comment by mrmeku** [comment]
That's a wonderful discovery! That gives me something to play around with at least. We can try a couple things to start

1) Using experimental hardlinks via a bazel flag
2) Copying a parent directory rather than the Cypress.app directory
3) Not copying on Mac OS (and giving up the ability to do RBE on Mac remote executors)

I'll run some experiments and see which option works. In the worst case, it seems like you've proven that #3 works :)

**Comment by KatSick** [comment]
here is a repository to reproduce the issue https://github.com/KatSick/rules_cypress_bug_macos
